### ISSUE TITLE
Helm install fails v1.9.0: Init:CrashLoopBackOff on harbor-harbor-database-0

### ISSUE THREAD

**Issue by mizhkeao** [goharbor/harbor-helm#373] opened 2019-09-24 11:19 UTC
Running ```helm install --name harbor harbor/harbor``` fails, it seems that the busybox container is unable to complete [change-permission-of-directory:], where it attempts to modify permissions of the folder /var/lib/postgresql/data. 

```sh
[root@node1 ~]# kubectl describe pod harbor-harbor-database-0
Name:           harbor-harbor-database-0
Namespace:      default
Priority:       0
Node:           node6/192.168.199.238
Start Time:     Tue, 24 Sep 2019 19:08:18 +0800
Labels:         app=harbor
                chart=harbor
                component=database
                controller-revision-hash=harbor-harbor-database-7594bf6895
                heritage=Tiller
                release=harbor
                statefulset.kubernetes.io/pod-name=harbor-harbor-database-0
Annotations:    checksum/secret: 8accf53dfbf601db7e1b0fb79823d057c19b43014181ecc32c20f049f948b187
Status:         Pending
IP:             10.233.108.108
Controlled By:  StatefulSet/harbor-harbor-database
Init Containers:
  change-permission-of-directory:
    Container ID:  docker://6e45b05070db2caad52e4eefab8ec80e856d7c714247c830c753457b53a99512
    Image:         busybox:latest
    Image ID:      docker-pullable://busybox@sha256:fe301db49df08c384001ed752dff6d52b4305a73a7f608f21528048e8a08b51e
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      chown -R 999:999 /var/lib/postgresql/data
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 24 Sep 2019 19:08:37 +0800
      Finished:     Tue, 24 Sep 2019 19:08:37 +0800
    Ready:          False
    Restart Count:  2
    Environment:    <none>
    Mounts:
      /var/lib/postgresql/data from database-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lm9kh (ro)
  remove-lost-found:
    Container ID:
    Image:         goharbor/harbor-db:v1.9.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      rm
      -Rf
      /var/lib/postgresql/data/lost+found
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/postgresql/data from database-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lm9kh (ro)
Containers:
  database:
    Container ID:
    Image:          goharbor/harbor-db:v1.9.0
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       exec [/docker-healthcheck.sh] delay=60s timeout=1s period=10s #success=1 #failure=3
    Readiness:      exec [/docker-healthcheck.sh] delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      harbor-harbor-database  Secret  Optional: false
    Environment:              <none>
    Mounts:
      /var/lib/postgresql/data from database-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lm9kh (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  database-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  database-data-harbor-harbor-database-0
    ReadOnly:   false
  default-token-lm9kh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lm9kh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  43s (x2 over 43s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 6 times)
  Normal   Scheduled         41s                default-scheduler  Successfully assigned default/harbor-harbor-database-0 to node6
  Normal   Pulled            22s (x3 over 39s)  kubelet, node6     Container image "busybox:latest" already present on machine
  Normal   Created           22s (x3 over 39s)  kubelet, node6     Created container change-permission-of-directory
  Normal   Started           22s (x3 over 38s)  kubelet, node6     Started container change-permission-of-directory
  Warning  BackOff           5s (x5 over 37s)   kubelet, node6     Back-off restarting failed container
```

```sh
[root@node1 ~]# kubectl get pods
NAME                                                 READY   STATUS                  RESTARTS   AGE
harbor-harbor-chartmuseum-64f97c484b-2wq5s           0/1     CrashLoopBackOff        5          4m52s
harbor-harbor-clair-7b5c45f5f4-sddlb                 0/1     CrashLoopBackOff        5          4m52s
harbor-harbor-core-6c88b475bf-x9ntv                  0/1     Running                 5          4m52s
harbor-harbor-database-0                             0/1     Init:CrashLoopBackOff   5          4m52s
harbor-harbor-jobservice-785ff7d74d-gfz8j            0/1     Running                 5          4m52s
harbor-harbor-notary-server-c6cdf685c-589s5          0/1     CrashLoopBackOff        4          4m52s
harbor-harbor-notary-signer-855876bb8f-l8bk2         0/1     CrashLoopBackOff        4          4m52s
harbor-harbor-portal-64bc45998-mzzgg                 1/1     Running                 0          4m52s
harbor-harbor-redis-0                                1/1     Running                 0          4m51s
harbor-harbor-registry-89c775cc9-z9k2k               0/2     CrashLoopBackOff        10         4m52s
nfs-client-nfs-client-provisioner-79c794d5f5-b4ljr   1/1     Running                 0          3h22m
```

Seems like pv and pvc have been bound successfully as well.
```sh
[root@node1 ~]# kubectl get pvc
NAME                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-harbor-harbor-redis-0               Bound    pvc-af48c87b-bace-4e35-8431-005c3d3047fd   1Gi        RWO            nfs-client     5m6s
database-data-harbor-harbor-database-0   Bound    pvc-b9587941-0019-4dac-9d54-4559989eea67   1Gi        RWO            nfs-client     5m7s
harbor-harbor-chartmuseum                Bound    pvc-5b5a2fb9-3ddd-4cb4-9575-8103efd4c85d   5Gi        RWO            nfs-client     5m8s
harbor-harbor-jobservice                 Bound    pvc-28855c13-dba7-4397-8f86-ff7536f66dd8   1Gi        RWO            nfs-client     5m8s
harbor-harbor-registry                   Bound    pvc-f6b22592-39bc-496d-8565-684d44c50849   5Gi        RWO            nfs-client     5m8s
test-claim                               Bound    pvc-ff42d808-eb75-4ea3-ad13-128cb4b9434d   1Mi        RWX            nfs-client     3h50m

[root@node1 ~]# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                            STORAGECLASS   REASON   AGE
pvc-28855c13-dba7-4397-8f86-ff7536f66dd8   1Gi        RWO            Delete           Bound    default/harbor-harbor-jobservice                 nfs-client              5m12s
pvc-5b5a2fb9-3ddd-4cb4-9575-8103efd4c85d   5Gi        RWO            Delete           Bound    default/harbor-harbor-chartmuseum                nfs-client              5m12s
pvc-af48c87b-bace-4e35-8431-005c3d3047fd   1Gi        RWO            Delete           Bound    default/data-harbor-harbor-redis-0               nfs-client              5m9s
pvc-b9587941-0019-4dac-9d54-4559989eea67   1Gi        RWO            Delete           Bound    default/database-data-harbor-harbor-database-0   nfs-client              5m10s
pvc-f6b22592-39bc-496d-8565-684d44c50849   5Gi        RWO            Delete           Bound    default/harbor-harbor-registry                   nfs-client              5m12s
pvc-ff42d808-eb75-4ea3-ad13-128cb4b9434d   1Mi        RWX            Delete           Bound    default/test-claim                               nfs-client              3h22m
```

**Comment by ywk253100** [comment] 2019-09-25 02:09
Check the log of the init container `change-permission-of-directory`

**Comment by mizhkeao** [comment] 2019-09-25 02:27
Hi @ywk253100, the logs are
```
chown: '/chart_storage' to '10000:10000': Operation not permitted
```
Is the busybox container missing permissions to create the directory somehow?

**Comment by deef0000dragon1** [comment] 2019-11-28 07:17
I have also encountered this, though my logs are 

> chown: /var/lib/postgresql/data: Invalid argument

**Comment by deef0000dragon1** [comment] 2019-11-28 15:38
testing with an older version of the chart (1.1.6 vs 1.2.3/master) I get 

> 2019-11-28T15:36:19.580458891Z chown: changing ownership of '/var/lib/postgresql/data': Invalid argument

**Comment by deef0000dragon1** [comment] 2019-12-09 00:11
Doing a bit more research, it appears that this is a result of NFS PVC/storage classes not allowing change of permissions.

**Comment by fredcb** [comment] 2020-01-08 14:17
I get the same issue even thoug I configured persistence.enabled=false, i.e no PVC.
I think the problem is due to the fact that the container is started as non-root. The command 
"chown -R 999:999 /var/lib/postgresql/data" will naturally fail then.

**Comment by BoMarconiHenriksen** [comment] 2020-01-13 12:16
I have the same problem when installing Harbor. The log of the harbor-harbor-database is:

> chown: /var/lib/postgresql/data/.snapshot/5min.2020-01-13_1155: Read-only file system
chown: /var/lib/postgresql/data/.snapshot/5min.2020-01-13_1155: Resource temporarily unavailable
chown: /var/lib/postgresql/data/.snapshot: Read-only file system
chown: /var/lib/postgresql/data/.snapshot: Read-only file system

**Comment by fredcb** [comment] 2020-01-13 14:29
I found that this problem is related to Openshift and  security configuration. To allow an image to run with the user specified in the dockerfile you have to specifically allow that. See https://docs.openshift.com/container-platform/3.11/admin_guide/manage_scc.html

**Comment by bravosierrasierra** [comment] 2020-02-17 12:44
We can just use external database via database.external chart property. 
Another workaround for permissions: PGDATA option for chart, pointed to /var/lib/postgresql/data/data, but this need chart rewrite.

**Comment by reasonerjt** [comment] 2020-06-20 17:23
It seems the same symptom may be caused by different problems.

Most likely it's the env that do not allow `chown`,  in that case you have to make sure the directory in the volume has the permission required by the pod.

@deef0000dragon1 @fredcb Thanks for providing the fix.

I'm closing this issue.

**Closed by reasonerjt** 2020-06-20 17:23 UTC
