### ISSUE TITLE
Filed to export CVE 

### ISSUE THREAD

**Issue by nevlkv** [goharbor/harbor-helm#1444] opened 2023-03-10 13:20 UTC
harbor 2.7.1
helm chart 1.11.1
OIDC auth

On try export project cve summary
![image](https://user-images.githubusercontent.com/46656585/224325713-175550c2-4d6d-4ca0-a87e-e10ca8dc1770.png)

jobservice log
```
2023-03-10T13:10:27Z [ERROR] [/pkg/systemartifact/manager.go:111]: Error creating system artifact record for scan_data_export/scandata_export_1.879364e+06/sha256:3c7607312d6faf63f863d13fa76fd8b2e25df6b9c6c513ac3938807fc6e36c48: http status code: 404, body: 404 page not found
2023-03-10T13:10:27Z [ERROR] [/jobservice/runner/redis.go:123]: Job 'SCAN_DATA_EXPORT:d2ac1180917b5041c860b560' exit with error: run error: http status code: 404, body: 404 page not found
```

**Comment by nevlkv** [comment] 2023-03-13 09:29
```
  REPO_NAME: "harbor"
  REPO_URL: "https://helm.goharbor.io"
  CHART_NAME: "harbor"
  VERSION: "1.11.1"
  ```
  
```
cat ./harbor/templates/jobservice/jobservice-pvc.yaml 
{{- $jobLog := .Values.persistence.persistentVolumeClaim.jobservice.jobLog -}}
{{- if and .Values.persistence.enabled (not $jobLog.existingClaim) (has "file" .Values.jobservice.jobLoggers) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "harbor.jobservice" . }}
  annotations:
  {{- range $key, $value := $jobLog.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: jobservice
spec:
  accessModes: 
    - {{ $jobLog.accessMode }}
  resources:
    requests:
      storage: {{ $jobLog.size }}
  {{- if $jobLog.storageClass }}
    {{- if eq "-" $jobLog.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $jobLog.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
```

job service without PV logs stored in database

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "18"
    meta.helm.sh/release-name: harbor
    meta.helm.sh/release-namespace: io
  creationTimestamp: "2022-06-27T07:15:48Z"
  generation: 25
  labels:
    app: harbor
    app.kubernetes.io/managed-by: Helm
    chart: harbor
    component: jobservice
    heritage: Helm
    release: harbor
  name: harbor-jobservice
  namespace: io
  resourceVersion: "2661802036"
  uid: 7c4b8040-606f-44e1-9cc1-fb4ef6209c59
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: harbor
      component: jobservice
      release: harbor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configmap: 6c3aede46da25e50fb63af9285223b62e61c36186d3731db35537d4a77579b84
        checksum/configmap-env: 00913ffdc5ee705116234987fd9a28b1e47f0fc1e29a760f156aa1eb91e7f277
        checksum/secret: 12ec84d0bce89b6506307983d197289b732d9fc0dd2d304c34d5cef8fa08589d
        checksum/secret-core: f50f17afd4930722d3fb9e4c45c333e45785a62fb2b55a62510f030874b69074
        prometheus.io/port: "8001"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: harbor
        chart: harbor
        component: jobservice
        heritage: Helm
        release: harbor
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: CORE_SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: harbor-core
        envFrom:
        - configMapRef:
            name: harbor-jobservice-env
        - secretRef:
            name: harbor-jobservice
        image: goharbor/harbor-jobservice:v2.7.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/stats
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: jobservice
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/stats
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/jobservice/config.yml
          name: jobservice-config
          subPath: config.yml
        - mountPath: /var/log/jobs
          name: job-logs
      dnsPolicy: ClusterFirst
      nodeSelector:
        role: worker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          defaultMode: 420
          name: harbor-jobservice
        name: jobservice-config
      - emptyDir: {}
        name: job-logs

```
  

```
2023-03-13T09:22:26Z [ERROR] [/pkg/systemartifact/manager.go:111]: Error creating system artifact record for scan_data_export/scandata_export_1.90177e+06/sha256:5d8f11a2f4934cd442f87518638260873e40b05198909ced081502b27c747810: http status code: 404, body: 404 page not found
2023-03-13T09:22:26Z [ERROR] [/jobservice/runner/redis.go:123]: Job 'SCAN_DATA_EXPORT:20cbfd99fd87c46b6f484f94' exit with error: run error: http status code: 404, body: 404 page not found
```
scandata_export PV removed after upgrade from 1.10.3

**Comment by Vad1mo** [comment] 2023-03-20 21:24
related https://github.com/goharbor/harbor-helm/issues/1320

**Comment by zyyw** [comment] 2023-03-23 05:57
duplicate of this issue:
* https://github.com/goharbor/harbor/issues/18380
There is a PR trying to fix it:
* https://github.com/goharbor/harbor/pull/18398

**Closed** 2023-04-06 07:50 UTC
