### ISSUE TITLE
Harbor upgrade v1.8 to v1.9 issues

### ISSUE THREAD

**Issue by liquid-cloud** [goharbor/harbor-helm#371] opened 2019-09-24 09:45 UTC
We've upgraded our registry from v1.8.1 to v.1.9.0.

During the upgrade phase, we encountered the following:

- The pods were getting terminated before the migration was complete. Reason being that the threshold for the liveliness probe was too small to allow the migration to complete. The default `failureThreshold` is `3` ([reference](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes))  which makes the core container to get killed after one minute if it's not ready according to [the code](https://github.com/goharbor/harbor-helm/blob/master/templates/core/core-dpl.yaml#L37-L42).
Example log from the core container when this happens:
```
2019-09-24T07:11:13Z [INFO] [/core/main.go:146]: capture system signal terminated, to close "closing" channel
2019-09-24T07:11:16Z [INFO] [/core/main.go:152]: Timeout waiting goroutines to exit
```

- Having multiple core containers with version 1.9 starting up (possibly from scaling down and scaling up the deployment manually) can lead to database corruption. We've learned this the hard way unfortunately. We managed to restore a snapshot of the database and continue with the upgrade.

During the upgrade I suggest you take into consideration on how slow the storage is. We have around 400GB image data and 5000+ artifacts in total.

It took roughly ~7 minutes to persist the data for a project with ~1800 artifact count and ~210GB quota according to the new UI.

In total it the upgrade took ~20 minutes to persist the data:
```
2019-09-20T09:41:30Z [INFO] [/core/api/quota/migrator.go:111]: [Quota-Sync]:: start to persist data for server ... [registry]
.......
2019-09-20T09:59:07Z [INFO] [/core/api/quota/migrator.go:116]: [Quota-Sync]:: success to persist data for server ... [registry]
2019-09-20T09:59:10Z [INFO] [/core/main.go:107]: Success to sync quota data .....
2019/09/20 09:59:10 [I] [asm_amd64.s:1337] http server Running on http://:8080
```

**Comment by yevhenvolchenko** [comment] 2019-09-26 07:46
I think, that liveliness probe implemented incorrectly.
Now it's pointing at the same endpoint, as readiness does, so when the pod is running migrations is in non-live state, when it actually does.
**Pod should return 200 on liveliness during migrations** to avoid this issue in future.

**Comment by ywk253100** [comment] 2019-09-26 08:19
@yevhenvolchenko Good point!
But currently the HTTP server doesn't start until the migration work is done. Anyway, we'll consider this solution.

**Comment by mumrau** [comment] 2019-09-26 11:36
I agree with the workaround, if I understood well, to put the readiness at the same endpoint as the liveness with a much larger failure toleration. Even though the durations could be very hard to pick.
On the other hand, it is pretty clear for users that `harbor` itself is _not_ a micro-service, and they probably shouldn't expect a lighting-fast complete deployment in seconds.
It already is the case, on deployment some pod are restarted because they miss their sibling component, etc, which takes time to provision a complete working stack....

I'd rather have (and I think we all do), safety on data and migrations than speed up start-time on a component this stateful and possibly critical.

**Comment by ywk253100** [comment] 2019-10-17 02:37
@liquid-cloud @yevhenvolchenko @mumrau A configuration item `core.livenessProbe.initialDelaySeconds` has been added in Harbor chart 1.2.1, you can set it according to the artifact count to avoid the upgrade failure.

I'm closing this issue, feel free to reopen it if the issue isn't fix.

**Closed by ywk253100** 2019-10-17 02:37 UTC
Labels: target/1.9.1
