### ISSUE TITLE
Harbor PersistentVolumeClaims names changed in 2.3.0

### ISSUE THREAD

**Issue by kengibous** [goharbor/harbor-helm#987] opened 2021-06-24 16:03 UTC
It appears the names used for the persistentvolumeclaims changed when I upgraded from Harbor v2.2.2 (Chart 1.6.2) to Harbor v2.3.0 (Chart 1.7.0)

The names of the PVCs in v2.2.2 where

data-harbor-harbor-redis-0
data-harbor-harbor-trivy-0
database-data-harbor-harbor-database-0
harbor-harbor-chartmuseum
harbor-harbor-jobservice 
harbor-harbor-registry

Upgrading to v2.3.0 created new PVCs with names

data-harbor-redis-0
data-harbor-trivy-0
database-data-harbor-database-0
harbor-chartmuseum
harbor-jobservice 
harbor-registry

This is problematic because all the existing data is in the previously named pvcs - could this be related to the changes in 

https://github.com/goharbor/harbor-helm/commit/db7b7c17c20c6046c031abacc9dda6aef57e90a6#diff-87d68c754766af8e2e930e653be7e4b75fa0c8bdb187cb1bec293f265d9159ff

Looks like changes to the **harbor.fullname** might have changed the naming convention for the pvc names

**Comment by yannickb85** [comment] 2021-06-30 12:49
We had the same issue as @kengibous when upgrading from v2.2.2 to v2.3.0 using the 1.7.0 helm chart. 

The name of the 3 PVCs attached to the redis, trivy and database components changed. During the upgrade, PVCs with the new names were created (empty).

We had to manually move the data from the old PVCs to the newly created ones to restore our redis/trivy/database data correctly.

Note that we were not using the "persistence -> persistentVolumeClaim -> database/redis/trivy -> existingClaim" properties in our values.yaml overrides. I guess that could've solved our issue as well..

**Comment by titou10titou10** [comment] 2021-06-30 13:02
In fact, the name of all componenIs changed, so the change in`StatefulSet`PVC names
It seems it is possible to override the base name for components with value`"nameOverride"`but this value is nowhere documented and it is not present in`"values.yaml"`, only in `"_helpers.tpl"`
It shoud be in`values.yaml"`, documented and in changelog

**Comment by ninjadq** [comment] 2021-07-08 08:16
@ywk253100 should we need to mention this in the release note?

**Comment by ywk253100** [comment] 2021-07-19 08:07
Just mentioned by @kengibous , the issue is caused by the naming convention change introduced by https://github.com/goharbor/harbor-helm/commit/db7b7c17c20c6046c031abacc9dda6aef57e90a6#diff-87d68c754766af8e2e930e653be7e4b75fa0c8bdb187cb1bec293f265d9159ff in Harbor chart 1.7.0

If installing the Harbor chart(1.6-) with a release name that contains `harbor`, e.g. `my-harbor`, and trying to upgrade it to 1.7+ you will get the same issue here.

The workaround is performing the upgrade with the setting `fullnameOverride: my-harbor-harbor` in `values.yaml` or `--set` option

**Comment by ywk253100** [comment] 2021-07-19 08:56
Updated the release notes and upgrade documentation, closing this issue

**Closed by ywk253100** 2021-07-19 08:56 UTC

**Comment by SamDecrock** [comment] 2022-05-05 09:43
Can this be added to the to the Helm upgrade page: https://goharbor.io/docs/2.0.0/administration/upgrade/helm-upgrade/ ?
