### ISSUE TITLE
adminserver not working with external database with SSL

### ISSUE THREAD

**Issue by DevOpsCow** [goharbor/harbor-helm#59] opened 2018-10-16 23:42 UTC
Using branch 0.3.0 as "stable" is empty and "master" is under heavy development.

Deploying the helm char with:
Helm v2.11.0
Kubernetes v1.11.3

Initial test with SSL disabled worked perfectly fine.
Then:
1- edit values.yaml, update `database.external.sslmode` to `require`
2- All pods (except for adminserver) start up fine.
3- Notary completes migrations, everything is looking good so far everywhere else
4- adminserver stays in `CrashLoopBackOff`

adminserver logs:
```
2018-10-16T22:56:19Z [INFO] initializing system configurations...
2018-10-16T22:56:19Z [FATAL] [main.go:46]: failed to initialize the system: pq: no pg_hba.conf entry for host "<ip address>", user "<username>", database "<core_database>", SSL off
```

As you can see from the error "SSL off", looks like the adminserver is not applying the "SSL require" value properly (Notary does work with that). Checking the configmap `harbor-harbor-adminserver` it does shows the value on it: `POSTGRESQL_SSLMODE: require`

Also tried with `prefer`, same results for adminserver, and notary containers won't come up.

Please check or let me know if I should use a different word (true, enable, enabled, etc?) on adminserver configmap.

Thanks

p.d.
Is this related to https://github.com/goharbor/harbor/issues/5843 ?
If yes, how can I get the fix into my helm chart?
Thanks again

**Comment by DevOpsCow** [comment] 2018-10-17 00:12
More info
On https://raw.githubusercontent.com/goharbor/harbor-helm/0.3.0/templates/_helpers.tpl I see there are entries for Clair, NotaryServer and NotarySigner, but none for `coreDatabase`.

Might this be the issue? :)

**Comment by ywk253100** [comment] 2018-10-17 06:31
Yes, it's related to https://github.com/goharbor/harbor/issues/5843. The issue is fixed in the master branch of Harbor repository https://github.com/goharbor/harbor.
The chart 0.3.0 doesn't support the flag as it uses Harbor 1.6.0. You can try the chart in the master branch, it should work but please notes that the branch is in development.

**Closed** 2018-10-23 06:40 UTC
