### ISSUE TITLE
harbor-portal Liveness probe failed: connection refused

### ISSUE THREAD

**Issue by DevThep** [goharbor/harbor-helm#323] opened 2019-08-19 05:32 UTC
The only pod not running for me is the harbor-portal when using the helm install command. I have tweaked the livenessProbe and readiness probe in my deployment yaml to 30s but it still does not seem to help

Output when describing pod:
```
Events:
  Type     Reason     Age                     From                                               Message
  ----     ------     ----                    ----                                               -------
  Normal   Scheduled  7m55s                   default-scheduler                                  Successfully assigned harbor/harbor-dev-harbor-portal-94f8d4cd7-xpxw8 to ip-xx-x-xx-xx.xx-xxxx-x.compute.internal
  Normal   Pulled     6m10s (x3 over 7m53s)   kubelet, ip-xx-x-xx-xx.xx-xxxx-x.compute.internal  Container image "goharbor/harbor-portal:dev" already present on machine
  Normal   Created    6m10s (x3 over 7m53s)   kubelet, ip-xx-x-xx-xx.xx-xxxx-x.compute.internal  Created container
  Normal   Started    6m10s (x3 over 7m53s)   kubelet, ip-xx-x-xx-xx.xx-xxxx-x.compute.internal  Started container
  Normal   Killing    6m10s (x2 over 7m)      kubelet, ip-xx-x-xx-xx.xx-xxxx-x.compute.internal  Killing container with id docker://portal:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy  5m30s (x8 over 7m20s)   kubelet, ip-xx-x-xx-xx.xx-xxxx-x.compute.internal  Liveness probe failed: Get http://10.0.22.16:80/: dial tcp 10.0.22.16:80: connect: connection refused
  Warning  Unhealthy  2m51s (x13 over 7m21s)  kubelet, ip-xx-x-xx-xx.xx-xxxx-x.compute.internal  Readiness probe failed: Get http://10.0.22.16:80/: dial tcp 10.0.22.16:80: connect: connection refused
```

Any help would be appreciated.

**Comment by ywk253100** [comment] 2019-08-19 06:40
It is a known issue caused by the improvement to run containers with non-root user and it will be fixed by #324.
BTW, don't use the chart on master branch which is unstable. Follow the doc https://github.com/goharbor/harbor-helm#installation to install the stable version instead.

**Closed** 2019-08-19 06:40 UTC
