### ISSUE TITLE
Failed to get total of charts under project library: unauthorized after redeploy

### ISSUE THREAD

**Issue by mpostument** [goharbor/harbor-helm#157] opened 2019-02-14 16:48 UTC
Harbor is built using external redis, postgres with ingress controler. 
After i am doing upgrade even without any configuration changes after harbor speen up user not able to see projects.
![harbor](https://user-images.githubusercontent.com/9252594/52802299-574f2180-3088-11e9-81ce-e2b73a8f9688.png)
Logs from core container:
```
2019-02-14T16:39:59Z [DEBUG] [security.go:246]: creating local database security context...
2019-02-14T16:39:59Z [DEBUG] [project.go:196]: query sql:select count(1)  from project as p where p.deleted=false
2019-02-14T16:39:59Z [DEBUG] [project.go:173]: query sql:select distinct p.project_id, p.name, p.owner_id,
				p.creation_time, p.update_time  from project as p where p.deleted=false
2019-02-14T16:39:59Z [DEBUG] [handler_repo.go:165]: Getting index.yaml from 'http://harbor-ha-harbor-chartmuseum/library/index.yaml'
2019-02-14T16:39:59Z [ERROR] [project.go:426]: Failed to get total of charts under project library: unauthorized
```
Logs from chartmuseum
```
{"L":"ERROR","T":"2019-02-14T16:45:31.229Z","M":"[1195] Request served","path":"/library/index.yaml","comment":"","latency":"105.103µs","clientIP":"10.42.2.158","method":"GET","statusCode":401,"reqID":"410fe7be-72cd-4964-ab95-ad0ed0d8f1c4"}
```

After relaunch harbor using the same db and redis issue gone. But appear again after upgrade

**Comment by ywk253100** [comment] 2019-02-15 05:11
What is the version of Harbor chart you are using? This should have been fixed in #140 in master branch.

**Comment by ywk253100** [comment] 2019-02-15 05:13
As a workaround you can relaunch Harbor after doing upgrade just like what you have done.

**Comment by mpostument** [comment] 2019-02-15 05:13
i am using tag 1.0.0

**Comment by mpostument** [comment] 2019-02-15 05:15
Does it possible to publish a new release if there stable version?

**Comment by mpostument** [comment] 2019-02-15 05:22
Also, i found the secretkey value have value in kubernetes as not-a-secret even if I change the value in the helm.

**Comment by ywk253100** [comment] 2019-02-15 06:16
We have no plan to release a new version.
And I cannot reproduce the issue about the secretkey. Can you describe the steps how to reproduce it in detail?

**Comment by mpostument** [comment] 2019-02-15 06:18
Replace the value in variables, execute helm, check kubernetes secret for core and secretkey has default value

**Comment by ywk253100** [comment] 2019-02-25 02:45
Cannot reproduce.

**Comment by kyale** [comment] 2019-02-27 19:32
experiencing the smae issue on 1.0.0 running on Rancher

**Comment by ywk253100** [comment] 2019-03-06 02:47
@kyale As I have said in https://github.com/goharbor/harbor-helm/issues/157#issuecomment-463909141, this is a known issue in 1.0.0 and has been fixed in master. 

As a workaround, you can remove the current deploy but keep the PVCs and deploy it again with the new configurations and the existing PVCs.

**Closed** 2019-03-13 02:08 UTC

**Comment by QwertyJack** [comment] 2019-05-18 10:25
There is a better workaround to fix this: delete the pod of chartmuseum.
