### ISSUE TITLE
file permission issue for new installation using chart 1.5.2 1.5.3 and 1.6.0

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor-helm#881] opened 2021-03-05 00:28 UTC
when using chart 1.5.2 and 1.5.3, the trivy pod failed to start, with the following in its log:
```
{"built_at":"unknown","commit":"none","level":"info","msg":"Starting harbor-scanner-trivy","time":"2021-03-04T18:24:10Z","version":"dev"}
{"level":"warning","msg":"trivy cache dir does not exist","path":"/home/scanner/.cache/trivy","time":"2021-03-04T18:24:10Z"}
{"level":"fatal","msg":"Error: checking config: creating trivy cache dir: mkdir /home/scanner/.cache/trivy: permission denied","time":"2021-03-04T18:24:10Z"}
```
All the pvs are _brand new_.

Using chart 1.6.0, pods core, database, jobservice, notary server and notary signer would be in CrashLoopBackOff while the trivy pod in Error.  The database pod log includes the following:
```
initdb: could not create directory "/var/lib/postgresql/data/pgdata": Permission denied
```

When upgrading from chart 1.5.3 the new version of registry pod would be blocked by the old one, `Unable to attach or mount volumes: unmounted volumes=[registry-data], unattached volumes=[registry-data registry-htpasswd registry-config]: timed out waiting for the condition`.  We manually deleted the pod from the old deployment more than once before the new one was ok.

These error was observed on TKG 1.2 provisioned kubernetes on vSphere.

**Comment by rotbau** [comment] 2021-03-10 00:25
I hit the same error on TKG 1.2.  You are hitting a known issue.  I patched the vmware-csi-controller config as described in the document link and then deployment worked.  https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.2.1/rn/VMware-Tanzu-Kubernetes-Grid-121-Release-Notes.html#vsphere-issues-known

**Comment by nicolasery** [comment] 2021-03-13 12:30
Exact same situation, I had to pre-create the database root folder with chown 999:999 = postgres user on the database pod and give the storageclass name of the PVC database, deployed before ofc, in existingClaim database or the pod is not able to consume it, and now I have the trivy pod error as you @wu105

**Comment by nicolasery** [comment] 2021-03-13 12:42
@rotbau I'm on a k3s cluster, it seems a similar issue but I don't know how to fix it

**Comment by wu105** [comment] 2021-03-15 05:57
chown 10000:10000 would help trivy.

**Comment by wzfei012** [comment] 2021-03-15 13:38
I see,you haven't create a pvc for db  service or the pv is not empty.

**Comment by nicolasery** [comment] 2021-03-16 10:53
@wu105 ty alot it works now.
I don't know enough kubernetes to explain it, but dabatase and trivy need to overide owner's permissions so define just a PV for them to let the chart manage PVC from their storageClass doesn't work. A chart value like volumePermissions.enabled=true in the bitnami/postgresql chart would be nice if its possible.
I then define one PVC for database and one for trivy and it finally works

**Comment by reasonerjt** [comment] 2021-03-18 07:32
I believe the root cause is:
https://github.com/goharbor/harbor-helm/issues/881#issuecomment-794651040

Closing.

**Closed by reasonerjt** 2021-03-18 07:32 UTC
