### ISSUE TITLE
Jobservice logging to database is missing Postgres configuration

### ISSUE THREAD

**Issue by kvitajakub** [goharbor/harbor-helm#338] opened 2019-09-05 09:29 UTC
When configuring with option `jobservice.jobLogger=database` which lets jobservice write logs to postgres, querying for logs in API (`/api/replication/executions/7/tasks/6/log`) always return 500.

Chart is not providing Postgres connection details to the Jobservice Deployment/ConfigMap.

I managed to fix this by manually injecting POSTGRESQL_HOST, POSTGRESQL_PORT, POSTGRESQL_USERNAME, POSTGRESQL_PASSWORD environment variables. Then it starts working.

**Comment by ywk253100** [comment] 2019-09-06 02:06
The Jobservice gets the database information from the Core. Could you provide the logs when you getting the 500 error? I cannot reproduce the issue in my own environment.

**Comment by kvitajakub** [comment] 2019-09-17 10:59
I raised this on Slack and Steven Zou recommended going here: https://cloud-native.slack.com/archives/CC1E09J6S/p1567433554042900

Core log:
```
2019-09-02T13:15:51Z [ERROR] [/common/api/base.go:228]: failed to get log of task 6: http error: code 500, message {"code":10009,"message":"failed to get the job log","details":"\u003cQuerySeter\u003e no row found"}
```
Jobservice log:
```
2019-09-02T13:15:51Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'GET /api/v1/jobs/c1321014bf6ca6385b76dafb/log' error: 500 {"code":10009,"message":"failed to get the job log","details":"\u003cQuerySeter\u003e no row found"}
```

**Comment by ywk253100** [comment] 2019-09-25 03:14
The error `no row found` is a database error, which means the database is connected already.
For your issue, maybe caused by the job log sweeper, which sweeps the logs longer than 14 days.

I'm closing the issue, feel free to open it if it isn't your case

**Closed by ywk253100** 2019-09-25 03:14 UTC

**Comment by kvitajakub** [comment] 2019-09-25 15:14
I was creating brand new environment when I saw this problem and I was getting it at all jobs even ones I triggered at that time.. Also messages cleared up and everything started working after I manually added Postgres connection details to the jobservice.

I'm not particularly familiar with the Harbor codebase, can you show me how is it pulling details from core? I never seen pattern like this.

**Comment by ywk253100** [comment] 2019-09-26 02:23
Init job context: 
https://github.com/goharbor/harbor/blob/master/src/jobservice/main.go#L71
Get database configuration: https://github.com/goharbor/harbor/blob/master/src/jobservice/job/impl/context.go#L81

**Comment by kvitajakub** [comment] 2019-09-27 14:48
Thank you for the links, interesting stuff.

I'm not seeing this problem anymore after deploying Harbor 1.9.0. Maybe the issue was only on 1.8.2. so I'm not going to reopen the issue.

**Comment by legal90** [comment] 2019-12-12 14:28
Hi guys!
I'm seeing this error on Harbor 1.9.3, but only for push-based replication jobs which are in `In Progress` status. As stated in the first message, the API request like `/api/replication/executions/7/tasks/6/log ` returns 500.

But as soon as the job is completed, the requests returns the log successfully.

Is that how it is supposed to be? Or is it a bug?
